### ISSUE TITLE
Sensor for energie usage (in kWh and/or m3)

### ISSUE THREAD

**Issue by herwinjan** [msvisser/remeha_home#21]
Hi,

Can you add a sensor for the energie usage of the device?
in m3 and/or kWh?

Thanx!

**Comment by HanSyt** [comment]
Not sure if this is very useful, energy usage in the Remeha app is very inaccurate and way off the real usage in the P1 meter.

**Comment by herwinjan** [comment]
Shure, but I don't have a P1 meter :) So for me it is a sort of useful!

**Comment by HanSyt** [comment]
I had a look at it, according to the Remeha app on my phone I used 52m3 gas (45m3 heating and 7m3 hot water).
My P1 meter recorded 14.6m3, Engie has recorded 14.25m3 (difference is todays usage).

So that is the reason I think usage from the api will not very useful (it is more then 300% off the real values).

**Comment by msvisser** [comment]
From what I've seen, the energy API is very complex and probably hard to integrate well with Home Assistant. Furthermore, I agree with @HanSyt that the measurements seem to be way off, so I doubt it will be useful. So I'm currently not planning on integrating this feature.

If anyone wants to integrate this, I'm open to a PR.

**Comment by gdesmott** [comment]
> I had a look at it, according to the Remeha app on my phone I used 52m3 gas (45m3 heating and 7m3 hot water) for may 2023.

Out of curiosity, did you setup anything special to get the gas water consumption? I keep getting `0 m3/kwh` in the Remeha app.
