### ISSUE TITLE
integration failing to load

### ISSUE THREAD

**Issue by gdesmott** [msvisser/remeha_home#36]
The integration uses to be working fine but is no longer loading, displaying the _"Failed setup, will retry"_ error.

The only log I can find related to this integration is:

```
Logger: homeassistant.config_entries
Source: config_entries.py:441
First occurred: 12:04:44 (1 occurrences)
Last logged: 12:04:44
Config entry '$MY_EMAIL ' for remeha_home integration not ready yet; Retrying in background
```

**Comment by msvisser** [comment]
I think that most of the time this is caused by the API returning an error when we try to get data. Could you try adding in a log statement in `coordinator.py` after line 45. Something like `_LOGGER.warning("Unable to get API data because of: %s", err)`.

Let me know what type of error the API is giving you.

**Comment by gdesmott** [comment]
Thanks for your reply.

The integration is now working (while I didn't change anything), so I'll check next time it fails.

I guess those logs could be added upstream anyway? That seems like useful info to log.
