### ISSUE TITLE
Consumption sensors BETA

### ISSUE THREAD

**Issue by msvisser** [msvisser/remeha_home#41]
This issue can be used to post problems with the beta versions ([v0.1.14b0](https://github.com/msvisser/remeha_home/releases/tag/v0.1.14b0)) containing the consumption sensors. The beta version can be installed via HACS and then the consumption sensors can be enabled under the "home" entity of the integration.

**Comment by msvisser** [comment]
I have just released [v0.1.14b1](https://github.com/msvisser/remeha_home/releases/tag/v0.1.14b1) which addresses an issue with fetching the consumption data around midnight, which would cause the complete integration to become unavailable for ~1.5 hours.

**Comment by m4v3r1ckNl** [comment]
Thanks for the quick fix. Downloaded and updated, no issues so far. Keep you posted.

**Comment by hugo-leij** [comment]
Hi @msvisser,

thnx again for this update! In the beginning was everything ok. Unfortunately all my entities are not reachable.

```
Logger: custom_components.remeha_home.coordinator
Source: helpers/update_coordinator.py:290
Integration: Remeha Home (documentation,
issues)
First occurred: 00:11:58 (46 occurrences)
Last logged: 00:57:45

Unexpected error fetching remeha_home data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers /update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/remeha_home/coordinator.py", line 87, in _async_update_data
    self.appliance_consumption_data[appliance_id] = consumption_data[
                                                    ^^^^^^^^^^^^^^^^^
IndexError: list index out of range
```

**Comment by msvisser** [comment]
@hugo-leij the error that you are experiencing is the same one I found. It should be fixed in v0.1.14b1. If that does not fix it for you, please let me know.

**Comment by p2923260** [comment]
The cost counters in the Energy dashboard do not get refreshed. I put a static price but the cost does not change, independently from the number of KWh.

<img width="1142" alt="image" src="https://github.com/msvisser/remeha_home/assets/147997761/5debf97f-191a-42c0-9b7d-4f3f3dfb1e27">
<img width="1082" alt="image" src="https://github.com/msvisser/remeha_home/assets/147997761/b3571941-12fe-451e-98c0-7435cc6f7000">

**Comment by p2923260** [comment]
Same issue also with b1 drop.
<img width="1119" alt="image" src="https://github.com/msvisser/remeha_home/assets/147997761/08e1523a-c120-466a-af25-c789e06cfb44">
<img width="1106" alt="image" src="https://github.com/msvisser/remeha_home/assets/147997761/34367446-79dd-4dc2-8666-8babc1119d02">

**Comment by msvisser** [comment]
@p2923260 that is weird behavior, as I don't think I have any control over the calculation of those values. What does the history of the sensors look like?

**Comment by p2923260** [comment]
Tonight Baxi server experienced some major glitches and Remeha reload failed multiple times randomly due to timeout. Also MyBaxi app had the same problem (tested on Wifi and 5G networks) so I assume it was not network related, I will retest tomorrow. 2023-11-22 20:20:18.090 ERROR (MainThread) [custom_components.remeha_home.coordinator] Timeout fetching remeha_home data.

When I had patched the 0.13 Remeha version manually from Github (1 week ago) the gas cost counters appeared to be working right. Since then I installed the beta version but I have also upgraded HA (11.2 and 11.3) so I cannot finger point anyone.
Just wondered if 0.14.b1 changed any entity format/type because the cost value appears to be always the same.

Looking for your directions what logs or counters I can provide to help.

**Comment by p2923260** [comment]
Had to revert to 0.13 unfortunately.
Baxi server failed multiple times and now they don't report measures any more. Using 0.14b1 fails uploading any resources so I had to revert back.
Any clue what happened cloud side?

**Comment by p2923260** [comment]
Remeha stopped providing power measures after this drop was deployed. 0.14b1 polling too frequent, you should keep hourly query?

**Comment by msvisser** [comment]
I'm not experiencing any issues with the power measurements on my personal Home Assistant setup. It has been working fine for the last week. It seems that the Remeha Home servers we overloaded/unavailable for a while, but right now it works fine for me.

@p2923260 are you still experiencing problems with the beta version right now?

**Comment by p2923260** [comment]
Beta version looks good but it collects only zero measures because Remeha does not collect them anymore.
Not a fault in your integration but I'm worried they disabled the counter collection. I also tried to cancel and create a new Remeha account but no way.
Just note the thermostat manages the measurement but Remeha cloud does not retrieve it. Can you see actual measures on your side?

**Comment by msvisser** [comment]
I'm not sure why you are not seeing any energy usage measurements. My personal setup has been working fine since the beginning, and I'm still seeing it update regularly. Can you see the usage information in the app, or is that also not working?

**Comment by p2923260** [comment]
Problem solved, I had to delete the Remeha thermostat device and reset it to factory settings. Now collecting measurements and reporting to HA. Your 0.14b1 works very well.

**Comment by jeroenvdd** [comment]
I'm getting
![image](https://github.com/msvisser/remeha_home/assets/6975276/90f98132-38ac-45bb-b46a-48bb4b164468)

now too, I should check the logs when it started :)

**Comment by Pirionfr** [comment]
0.14b1 working great on my side too

**Comment by msvisser** [comment]
Since there have not been any bug reports on 0.1.14b1, I'm closing this issue.
